[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shapemind"
version = "0.1.0"
description = "CLI tool for learning and task management"
authors = [
    {name="Saeed", email="sgdvlpr@gmail.com"}
]
dependencies = [
    "typer>=0.9",
    "tabulate",
    "jdatetime"
]

[project.scripts]
shapemind = "shapemind.cli:main"
